#!/bin/bash

current_dir=`pwd`

# install homebrew
if [ -z "$(which brew)" ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install basic programs
programs=(
  asdf
  bat
  delta
  exa
  fish
  fzf
  git
  hub
  neovim
  ripgrep
  terminal-notifier
  tig
  tree
  tmux
  wget
)
for program in ${programs[@]}; do
  if [ -z "$(brew list --formula | grep $program)" ]; then
    brew install $program

    if [ "$program" == "fzf" ]; then
      /usr/local/opt/fzf/install
    fi
  fi
done
# shims FTW
if [ -z "$(which reattach-to-user-namespace)" ]; then
  brew install reattach-to-user-namespace
fi

# change to fish shell
if [ "$SHELL" != "/usr/local/bin/fish" ]; then
  echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/fish
fi
# install fisherman
if [ ! -f ~/.config/fish/functions/fisher.fish ]; then
  curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
fi
# copy fish config
ln -sf "$current_dir/config/fish/config.fish" ~/.config/fish/config.fish
ln -sf "$current_dir/config/fish/fish_plugins" ~/.config/fish/fish_plugins
for file in $(ls config/fish/functions); do
  ln -sf "$current_dir/config/fish/functions/$file" ~/.config/fish/functions/$file_name
done

# asdf
if [ -z "$(asdf plugin list | grep direnv)" ]; then
  asdf plugin-add direnv
  asdf install direnv $(asdf list-all direnv | tail -n1)
  asdf global direnv $(asdf list direnv | tail -n1)
fi

# neovim
mkdir -p ~/.config/nvim
for file in $(ls "$current_dir/config/nvim"); do
  ln -sfh "$current_dir/config/nvim/$file" ~/.config/nvim
done
if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# snips
mkdir -p ~/.config/coc/ultisnips
for file in $(ls "$current_dir/config/coc/ultisnips"); do
  ln -sfh "$current_dir/config/coc/ultisnips/$file" ~/.config/coc/ultisnips
done

# karabiner elements custom modifications
mkdir -p ~/.config/karabiner/assets/complex_modifications
for file in $(ls "$current_dir/config/karabiner/complex_modifications"); do
  ln -sfh "$current_dir/config/karabiner/complex_modifications/$file" ~/.config/karabiner/assets/complex_modifications
done

# copy dot files to home dir
for file in \.*; do
  # skip .git, . and ..
  if [[ "${file}" != '.git' && "${file}" != '.gitignore' && "${file}" != '.' && "${file}" != '..' && "${file}" != '.config' ]]; then
    ln -sfh "$current_dir/$file" ~/$file
  fi
done
for file in $(ls "$current_dir/.config"); do
  ln -sfh "$current_dir/.config/$file" ~/.config/$file
done

mkdir -p ~/bin
for file in bin/*; do
  file_name=$(echo -n $file | sed "s#bin/##")
  ln -sf "$current_dir/$file" ~/bin/$file_name
done
