#!/bin/bash

current_dir=`pwd`
# copy files to home dir
for file in \.*; do
  # skip .git, . and ..
  if [[ "${file}" != '.git' && "${file}" != '.gitignore' && "${file}" != '.' && "${file}" != '..' ]]; then
    ln -sf "$current_dir/$file" ~/$file
  fi
done

ln -sf "$current_dir/mine.zsh" ~/.oh-my-zsh/custom/mine.zsh
ln -sf "$current_dir/mine.zsh-theme" ~/.oh-my-zsh/themes/mine.zsh-theme

mkdir -p ~/.vim/colors
ln -sf "$current_dir/my_colors.vim" ~/.vim/colors/my_colors.vim

ln -sfh "$current_dir/snippets" ~/.vim/snippets

mkdir -p ~/bin
ln -sf "$current_dir/bin/cb" ~/bin/cb
ln -sf "$current_dir/bin/tmux_battery_charge_indicator.rb" ~/bin/tmux_battery_charge_indicator.rb
